version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
